### ISSUE TITLE
Uno DM 3.3 TL Plus not working with v4.0.0

### ISSUE THREAD

**Issue by jagoman81** [alexdelprete/ha-abb-powerone-pvi-sunspec#291]
## System Information

version | core-2025.7.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
container_arch | amd64
user | root
virtualenv | false
python_version | 3.13.3
os_name | Linux
os_version | 6.12.35-haos
arch | x86_64
timezone | Europe/Bucharest
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4954
Installed Version | 2.0.5
Stage | running
Available Repositories | 2131
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 16.0
-- | --
update_channel | stable
supervisor_version | supervisor-2025.07.3
agent_version | 1.7.2
docker_version | 28.3.0
disk_total | 30.8 GB
disk_used | 6.0 GB
healthy | true
supported | true
host_connectivity | false
supervisor_connectivity | true
ntp_synchronized | false
virtualization | oracle
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Filebrowser (2.42.2-2), Terminal & SSH (9.18.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 0
views | 12
mode | storage

</details>

<details><summary>Network Configuration</summary>

adapters | lo (disabled), enp0s3 (enabled, default, auto), hassio (disabled), docker0 (disabled), vetha62b969 (disabled), veth2eb59a5 (disabled), veth2d3a0fb (disabled), veth5758cbb (disabled), veth2d289a5 (disabled), veth377afe2 (disabled), vethb475fbf (disabled)
-- | --
ipv4_addresses | lo (127.0.0.1/8), enp0s3 (192.168.1.158/24), hassio (172.30.32.1/23), docker0 (172.30.232.1/23), vetha62b969 (), veth2eb59a5 (), veth2d3a0fb (), veth5758cbb (), veth2d289a5 (), veth377afe2 (), vethb475fbf ()
ipv6_addresses | lo (::1/128), enp0s3 (fe80::57bf:232b:44a5:667f/64), hassio (fe80::b8e5:5aff:fe46:d3cc/64), docker0 (fe80::b04c:4fff:febb:7163/64), vetha62b969 (fe80::7c8a:dbff:fe6c:4eef/64), veth2eb59a5 (fe80::84b5:40ff:fe38:1c99/64), veth2d3a0fb (fe80::dc80:35ff:fe2d:3a83/64), veth5758cbb (fe80::38cd:afff:fe20:1e04/64), veth2d289a5 (fe80::5c1b:1eff:fef0:c99b/64), veth377afe2 (fe80::dc47:76ff:fed5:cc9/64), vethb475fbf (fe80::44d8:beff:fe56:8525/64)
announce_addresses | 192.168.1.158, fe80::57bf:232b:44a5:667f

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 25, 2025 at 3:19 PM
-- | --
current_recorder_run | August 9, 2025 at 5:19 PM
estimated_db_size | 923.02 MiB
database_engine | sqlite
database_version | 3.48.0

</details>

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After upgrading to V4.0.0 Integration does not load. Not even with beta.
Downgrading to 3.7.0 or 3.7.1 restores functionality.

### Reproduction steps

1. Downgrade to 3.7.0 makes is functioning
2. Upgrade to 4.0.0
3. Restart, and does not load
...

### Debug logs

```text
Cannot enable Debug logging, as Integration does not start, will include error log at Diagnostic dump
```

### Diagnostics dump

Error log

Logger: homeassistant.setup
Source: setup.py:343
First occurred: 5:20:02 PM (1 occurrence)
Last logged: 5:20:02 PM

Setup failed for custom integration 'abb_powerone_pvi_sunspec': Unable to import component: cannot import name 'pack_bitstring' from 'pymodbus.pdu.pdu' (/usr/local/lib/python3.13/site-packages/pymodbus/pdu/pdu.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 998, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1058, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/abb_powerone_pvi_sunspec/__init__.py", line 23, in <module>
    from .coordinator import ABBPowerOneFimerCoordinator
  File "/config/custom_components/abb_powerone_pvi_sunspec/coordinator.py", line 13, in <module>
    from .api import ABBPowerOneFimerAPI
  File "/config/custom_components/abb_powerone_pvi_sunspec/api.py", line 50, in <module>
    from .modbuspayload import BinaryPayloadDecoder
  File "/config/custom_components/abb_powerone_pvi_sunspec/modbuspayload.py", line 26, in <module>
    from pymodbus.pdu.pdu import (
    ...<2 lines>...
    )
ImportError: cannot import name 'pack_bitstring' from 'pymodbus.pdu.pdu' (/usr/local/lib/python3.13/site-packages/pymodbus/pdu/pdu.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1018, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1010, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1058, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/abb_powerone_pvi_sunspec/__init__.py", line 23, in <module>
    from .coordinator import ABBPowerOneFimerCoordinator
  File "/config/custom_components/abb_powerone_pvi_sunspec/coordinator.py", line 13, in <module>
    from .api import ABBPowerOneFimerAPI
  File "/config/custom_components/abb_powerone_pvi_sunspec/api.py", line 50, in <module>
    from .modbuspayload import BinaryPayloadDecoder
  File "/config/custom_components/abb_powerone_pvi_sunspec/modbuspayload.py", line 26, in <module>
    from pymodbus.pdu.pdu import (
    ...<2 lines>...
    )
ImportError: cannot import name 'pack_bitstring' from 'pymodbus.pdu.pdu' (/usr/local/lib/python3.13/site-packages/pymodbus/pdu/pdu.py)
